name: ppw
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0  
  http: ^1.3.0
  intl: ^0.17.0
  image_picker: ^1.0.7 
  location_picker_flutter_map: ^1.0.0
  flutter_map: ^6.0.0
  latlong2: ^0.9.1
  path_provider: ^2.0.14
  path: ^1.8.3
  url_launcher: ^6.2.5
  webview_flutter: ^4.2.2
  flutter_pdfview: ^1.2.5
  shared_preferences: ^2.0.15
  geocoding: ^2.1.1
  flutter_datetime_picker_bdaya: ^3.0.2
  get_storage: ^2.1.1
  cupertino_icons: ^1.0.8
  permission_handler: ^12.0.0+1
  cached_network_image: ^3.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/logo.png
    - assets/icon/main_logo.png

